
name: Pushing Dockerfile to Docker Hub

on:
  push:
    paths: docker/**
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          sha=$(git rev-parse --short HEAD)
          branch=$(git rev-parse --abbrev-ref HEAD)

          if [ "$branch" == "main" ]; then
            tag="latest"
          else
            tag="$branch-$sha"
          fi

          docker build -t maaclin99/repo1:$sha docker/
          docker push maaclin99/repo1:$sha
          
          docker tag maaclin99/repo1:$sha maaclin99/repo1:$tag
          docker push maaclin99/repo1:$tag
    